### ISSUE TITLE
Export statistics to PDF does not work for Manual projects

### ISSUE THREAD

**Issue by Kutepov** [valeriy-bashtovoy/motivate-clock-desktop#4]
v.1.6.0
Нажимая на кнопку экспорта, появляется окошко и далее ничего не происходит.

**Comment by bashtovoi** [comment]
Подскажите пожалуйста, это проблема возникает со всеми проектами, или только с некоторыми? У меня удалось воспроизвести только с проектом "Режим ручного учета".
Если нет ничего конфиденциального в проектах, то вышлите пожалуйста базу данных приложения на адрес info@motivateclock.org, она расположена в папке юзера:
\Users\%USER_NAME%\appData\Roaming\MotivateClock\Local Store\statistic.db

**Comment by Kutepov** [comment]
Спасибо, что откликнулись, отправил БД.
