### ISSUE TITLE
Time does not stop counting if OS goes into sleep/hibernate mode

### ISSUE THREAD

**Issue by bashtovoi** [valeriy-bashtovoy/motivate-clock-desktop#7]
Version: any;
Original issue: http://motivateclock.reformal.ru/proj/?ia=586920 (Issue has 18 votes);

**Comment by valeriy-bashtovoy** [comment]
Version: any;
Original issue: http://motivateclock.reformal.ru/proj/?ia=586920 (Issue has 18 votes);
